# environment.yml
name: quantms-rescoring
channels:
  - bioconda
  - conda-forge
  - nodefaults
dependencies:
  - python >=3.9
  - click
  - pyopenms>=3.0
  - pandas
  - numpy>=1.25
  - ms2rescore=3.1.4
  - deepLC>=3.0
  - psm-utils
  - scipy
  - pygam
  - protobuf
  - pytest
  - ms2pip>=4.0
