# environment.yml
name: quantms-rescoring
channels:
  - bioconda
  - conda-forge
  - nodefaults
dependencies:
  - python >=3.9
  - click
  - pyopenms>=2.4.0
  - pandas
  - numpy >= 2.0
  - ms2rescore=3.1.4
  - deepLC
  - psm-utils
  - scipy
  - pygam
  - protobuf
  - pytest
